repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        args: [--write]
        types_or:
          - yaml
          - json

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        types:
          - markdown

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.6.0
    hooks:
      - id: cspell

  - repo: local
    hooks:
      - id: taplo
        name: taplo
        language: system
        entry: taplo
        args:
          [
            fmt,
            --option,
            "array_auto_collapse=false",
            --option,
            "indent_string=    ",
          ]
        types:
          - toml
